"""add audit log, dsgvo, kostenstellen, ehrenamt

Revision ID: 24685f883256
Revises: e6e5b7df8262
Create Date: 2026-03-10 09:29:21.196540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24685f883256'
down_revision: Union[str, None] = 'e6e5b7df8262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aufwandsentschaedigungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('typ', sa.Enum('uebungsleiter', 'ehrenamt', name='aufwandtyp'), nullable=False),
    sa.Column('beschreibung', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglieder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kostenstellen',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abteilung_id', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['abteilung_id'], ['abteilungen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kostenstelle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_buchungen_kostenstelle_id', 'kostenstellen', ['kostenstelle_id'], ['id'])

    with op.batch_alter_table('mitglieder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dsgvo_einwilligung', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('einwilligung_datum', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('loesch_datum', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mitglieder', schema=None) as batch_op:
        batch_op.drop_column('loesch_datum')
        batch_op.drop_column('einwilligung_datum')
        batch_op.drop_column('dsgvo_einwilligung')

    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.drop_constraint('fk_buchungen_kostenstelle_id', type_='foreignkey')
        batch_op.drop_column('kostenstelle_id')

    op.drop_table('kostenstellen')
    op.drop_table('aufwandsentschaedigungen')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
