"""add trainer_lizenzen table

Revision ID: 77b9491321ce
Revises: 898efe4fb8bf
Create Date: 2026-03-10 22:32:45.139819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b9491321ce'
down_revision: Union[str, None] = '898efe4fb8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_lizenzen',
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('lizenztyp', sa.Enum('trainerlizenz_c', 'trainerlizenz_b', 'trainerlizenz_a', 'erste_hilfe', 'jugendleiter', 'rettungsschwimmer', 'sonstiges', name='lizenztyp'), nullable=False),
    sa.Column('bezeichnung', sa.String(length=300), nullable=False),
    sa.Column('ausstellungsdatum', sa.Date(), nullable=False),
    sa.Column('ablaufdatum', sa.Date(), nullable=False),
    sa.Column('lizenznummer', sa.String(length=100), nullable=True),
    sa.Column('ausstellende_stelle', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglieder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_lizenzen')
    # ### end Alembic commands ###
