"""add skonto and versand fields

Revision ID: 8912f74a08fe
Revises: fd493e37c0cf
Create Date: 2026-03-10 13:31:52.275645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8912f74a08fe'
down_revision: Union[str, None] = 'fd493e37c0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eingangsrechnungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rechnungsnummer', sa.String(length=50), nullable=False),
    sa.Column('aussteller_name', sa.String(length=200), nullable=False),
    sa.Column('aussteller_strasse', sa.String(length=200), nullable=True),
    sa.Column('aussteller_plz', sa.String(length=10), nullable=True),
    sa.Column('aussteller_ort', sa.String(length=100), nullable=True),
    sa.Column('aussteller_steuernr', sa.String(length=30), nullable=True),
    sa.Column('aussteller_ust_id', sa.String(length=20), nullable=True),
    sa.Column('rechnungsdatum', sa.Date(), nullable=False),
    sa.Column('faelligkeitsdatum', sa.Date(), nullable=True),
    sa.Column('leistungsdatum', sa.Date(), nullable=True),
    sa.Column('summe_netto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('summe_steuer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('summe_brutto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('waehrung', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('eingegangen', 'geprueft', 'freigegeben', 'bezahlt', 'abgelehnt', name='eingangsrechnungstatus'), nullable=False),
    sa.Column('kostenstelle_id', sa.Integer(), nullable=True),
    sa.Column('sphaere', sa.String(length=30), nullable=True),
    sa.Column('quell_format', sa.String(length=20), nullable=True),
    sa.Column('quell_xml', sa.Text(), nullable=True),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kostenstelle_id'], ['kostenstellen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rechnungen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skonto_prozent', sa.Numeric(precision=4, scale=2), nullable=True))
        batch_op.add_column(sa.Column('skonto_frist_tage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skonto_betrag', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('versand_kanal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('versendet_am', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('versendet_an', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rechnungen', schema=None) as batch_op:
        batch_op.drop_column('versendet_an')
        batch_op.drop_column('versendet_am')
        batch_op.drop_column('versand_kanal')
        batch_op.drop_column('skonto_betrag')
        batch_op.drop_column('skonto_frist_tage')
        batch_op.drop_column('skonto_prozent')

    op.drop_table('eingangsrechnungen')
    # ### end Alembic commands ###
