"""add_protokolle_table

Revision ID: 898efe4fb8bf
Revises: 1a7bd51899af
Create Date: 2026-03-10 22:22:30.645637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898efe4fb8bf'
down_revision: Union[str, None] = '1a7bd51899af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protokolle',
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('datum', sa.String(), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('typ', sa.Enum('vorstandssitzung', 'mitgliederversammlung', 'abteilungssitzung', 'sonstige', name='protokolltyp'), nullable=False),
    sa.Column('erstellt_von', sa.String(), nullable=True),
    sa.Column('teilnehmer', sa.Text(), nullable=True),
    sa.Column('beschluesse', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protokolle')
    # ### end Alembic commands ###
