"""initial models

Revision ID: db1c9f8f0f32
Revises: 
Create Date: 2026-03-10 08:17:58.062702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1c9f8f0f32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abteilungen',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('beitragskategorien',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('jahresbeitrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('beschreibung', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mitglieder',
    sa.Column('mitgliedsnummer', sa.String(length=20), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('geburtsdatum', sa.Date(), nullable=False),
    sa.Column('strasse', sa.String(length=200), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('eintrittsdatum', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('austrittsdatum', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('aktiv', 'passiv', 'gekuendigt', 'ehrenmitglied', name='mitgliedstatus'), nullable=False),
    sa.Column('beitragskategorie', sa.Enum('erwachsene', 'jugend', 'familie', 'passiv', 'ehrenmitglied', name='beitragkategorie'), nullable=False),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mitgliedsnummer')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('mitglied_abteilungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('abteilung_id', sa.Integer(), nullable=False),
    sa.Column('beitrittsdatum', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['abteilung_id'], ['abteilungen.id'], ),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglieder.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mitglied_id', 'abteilung_id', name='uq_mitglied_abteilung')
    )
    op.create_table('sepa_mandate',
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('mandatsreferenz', sa.String(length=35), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('kontoinhaber', sa.String(length=200), nullable=False),
    sa.Column('unterschriftsdatum', sa.Date(), nullable=False),
    sa.Column('gueltig_ab', sa.Date(), nullable=False),
    sa.Column('gueltig_bis', sa.Date(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglieder.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandatsreferenz')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sepa_mandate')
    op.drop_table('mitglied_abteilungen')
    op.drop_table('api_tokens')
    op.drop_table('mitglieder')
    op.drop_table('beitragskategorien')
    op.drop_table('admin_users')
    op.drop_table('abteilungen')
    # ### end Alembic commands ###
