"""add training and attendance models

Revision ID: e560917f6926
Revises: e7e4de2b9dc9
Create Date: 2026-03-10 12:30:34.464871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e560917f6926'
down_revision: Union[str, None] = 'e7e4de2b9dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingsgruppen',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('abteilung_id', sa.Integer(), nullable=False),
    sa.Column('trainer', sa.String(length=200), nullable=True),
    sa.Column('wochentag', sa.Enum('montag', 'dienstag', 'mittwoch', 'donnerstag', 'freitag', 'samstag', 'sonntag', name='wochentag'), nullable=False),
    sa.Column('uhrzeit', sa.String(length=5), nullable=False),
    sa.Column('dauer_minuten', sa.Integer(), nullable=False),
    sa.Column('max_teilnehmer', sa.Integer(), nullable=True),
    sa.Column('ort', sa.String(length=200), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['abteilung_id'], ['abteilungen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anwesenheiten',
    sa.Column('trainingsgruppe_id', sa.Integer(), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('anwesend', sa.Boolean(), nullable=False),
    sa.Column('notiz', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglieder.id'], ),
    sa.ForeignKeyConstraint(['trainingsgruppe_id'], ['trainingsgruppen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainingsgruppe_id', 'mitglied_id', 'datum', name='uq_anwesenheit_gruppe_mitglied_datum')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anwesenheiten')
    op.drop_table('trainingsgruppen')
    # ### end Alembic commands ###
