"""add finance and communication models

Revision ID: e6e5b7df8262
Revises: db1c9f8f0f32
Create Date: 2026-03-10 08:40:43.863341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e5b7df8262'
down_revision: Union[str, None] = 'db1c9f8f0f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nachrichten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('betreff', sa.String(length=300), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('typ', sa.Enum('email', 'brief', name='nachrichttyp'), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('gesendet_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buchungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buchungsdatum', sa.Date(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('beschreibung', sa.String(length=500), nullable=False),
    sa.Column('konto', sa.String(length=20), nullable=False),
    sa.Column('gegenkonto', sa.String(length=20), nullable=False),
    sa.Column('sphare', sa.Enum('ideell', 'zweckbetrieb', 'vermoegensverwaltung', 'wirtschaftlich', name='sphare'), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglieder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nachricht_empfaenger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nachricht_id', sa.Integer(), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ausstehend', 'gesendet', 'fehlgeschlagen', name='empfaengerstatus'), nullable=False),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglieder.id'], ),
    sa.ForeignKeyConstraint(['nachricht_id'], ['nachrichten.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rechnungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rechnungsnummer', sa.String(length=20), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('beschreibung', sa.String(length=500), nullable=False),
    sa.Column('rechnungsdatum', sa.Date(), nullable=False),
    sa.Column('faelligkeitsdatum', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('offen', 'bezahlt', 'ueberfaellig', 'storniert', name='rechnungstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglieder.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rechnungsnummer')
    )
    op.create_table('spendenbescheinigungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ausstellungsdatum', sa.Date(), nullable=False),
    sa.Column('zweck', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglieder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zahlungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rechnung_id', sa.Integer(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('zahlungsdatum', sa.Date(), nullable=False),
    sa.Column('zahlungsart', sa.Enum('lastschrift', 'ueberweisung', 'bar', name='zahlungsart'), nullable=False),
    sa.Column('referenz', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rechnung_id'], ['rechnungen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zahlungen')
    op.drop_table('spendenbescheinigungen')
    op.drop_table('rechnungen')
    op.drop_table('nachricht_empfaenger')
    op.drop_table('buchungen')
    op.drop_table('nachrichten')
    # ### end Alembic commands ###
