"""add freigabelimit and parent_buchung_id

Revision ID: e7e4de2b9dc9
Revises: 24685f883256
Create Date: 2026-03-10 10:08:20.245009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e4de2b9dc9'
down_revision: Union[str, None] = '24685f883256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_buchung_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_buchungen_parent_buchung_id', 'buchungen', ['parent_buchung_id'], ['id'])

    with op.batch_alter_table('kostenstellen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beschreibung', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('freigabelimit', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kostenstellen', schema=None) as batch_op:
        batch_op.drop_column('freigabelimit')
        batch_op.drop_column('beschreibung')

    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.drop_constraint('fk_buchungen_parent_buchung_id', type_='foreignkey')
        batch_op.drop_column('parent_buchung_id')

    # ### end Alembic commands ###
