"""expand rechnung model for legal compliance

Revision ID: fd493e37c0cf
Revises: e560917f6926
Create Date: 2026-03-10 12:54:48.141456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd493e37c0cf'
down_revision: Union[str, None] = 'e560917f6926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vereinsstammdaten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strasse', sa.String(length=200), nullable=False),
    sa.Column('plz', sa.String(length=10), nullable=False),
    sa.Column('ort', sa.String(length=100), nullable=False),
    sa.Column('steuernummer', sa.String(length=30), nullable=True),
    sa.Column('ust_id', sa.String(length=20), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('registergericht', sa.String(length=100), nullable=True),
    sa.Column('registernummer', sa.String(length=30), nullable=True),
    sa.Column('freistellungsbescheid_datum', sa.Date(), nullable=True),
    sa.Column('freistellungsbescheid_az', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rechnungspositionen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rechnung_id', sa.Integer(), nullable=False),
    sa.Column('position_nr', sa.Integer(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('menge', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('einheit', sa.String(length=20), nullable=False),
    sa.Column('einzelpreis_netto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('steuersatz', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('steuerbefreiungsgrund', sa.String(length=200), nullable=True),
    sa.Column('gesamtpreis_netto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gesamtpreis_steuer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gesamtpreis_brutto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kostenstelle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kostenstelle_id'], ['kostenstellen.id'], ),
    sa.ForeignKeyConstraint(['rechnung_id'], ['rechnungen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rechnungen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rechnungstyp', sa.Enum('mitgliedsbeitrag', 'kursgebuehr', 'hallenmiete', 'sponsoring', 'sonstige', 'storno', 'mahnung', name='rechnungtyp'), nullable=False, server_default='sonstige'))
        batch_op.add_column(sa.Column('mahnstufe', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('format', sa.Enum('pdf', 'zugferd', 'xrechnung', name='rechnungformat'), nullable=False, server_default='pdf'))
        batch_op.add_column(sa.Column('empfaenger_typ', sa.Enum('mitglied', 'sponsor', 'extern', name='empfaengertyp'), nullable=False, server_default='mitglied'))
        batch_op.add_column(sa.Column('empfaenger_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('empfaenger_strasse', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('empfaenger_plz', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('empfaenger_ort', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('empfaenger_ust_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('summe_netto', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('summe_steuer', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bezahlt_betrag', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('offener_betrag', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('leistungsdatum', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('leistungszeitraum_von', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('leistungszeitraum_bis', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('zahlungsziel_tage', sa.Integer(), nullable=False, server_default='14'))
        batch_op.add_column(sa.Column('gestellt_am', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bezahlt_am', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sphaere', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('steuerhinweis_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verwendungszweck', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('storno_von_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loeschdatum', sa.Date(), nullable=True))
        batch_op.alter_column('rechnungsnummer',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('mitglied_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('entwurf', 'gestellt', 'faellig', 'mahnung_1', 'mahnung_2', 'mahnung_3', 'bezahlt', 'teilbezahlt', 'storniert', 'abgeschrieben', name='rechnungstatus'),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_rechnungen_storno_von_id', 'rechnungen', ['storno_von_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rechnungen', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rechnungen_storno_von_id', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('entwurf', 'gestellt', 'faellig', 'mahnung_1', 'mahnung_2', 'mahnung_3', 'bezahlt', 'teilbezahlt', 'storniert', 'abgeschrieben', name='rechnungstatus'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
        batch_op.alter_column('mitglied_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rechnungsnummer',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('loeschdatum')
        batch_op.drop_column('storno_von_id')
        batch_op.drop_column('verwendungszweck')
        batch_op.drop_column('steuerhinweis_text')
        batch_op.drop_column('sphaere')
        batch_op.drop_column('bezahlt_am')
        batch_op.drop_column('gestellt_am')
        batch_op.drop_column('zahlungsziel_tage')
        batch_op.drop_column('leistungszeitraum_bis')
        batch_op.drop_column('leistungszeitraum_von')
        batch_op.drop_column('leistungsdatum')
        batch_op.drop_column('offener_betrag')
        batch_op.drop_column('bezahlt_betrag')
        batch_op.drop_column('summe_steuer')
        batch_op.drop_column('summe_netto')
        batch_op.drop_column('empfaenger_ust_id')
        batch_op.drop_column('empfaenger_ort')
        batch_op.drop_column('empfaenger_plz')
        batch_op.drop_column('empfaenger_strasse')
        batch_op.drop_column('empfaenger_name')
        batch_op.drop_column('empfaenger_typ')
        batch_op.drop_column('format')
        batch_op.drop_column('mahnstufe')
        batch_op.drop_column('rechnungstyp')

    op.drop_table('rechnungspositionen')
    op.drop_table('vereinsstammdaten')
    # ### end Alembic commands ###
